Feature: User is able to edit accessible tariff once per 30 days.
minsk-hackerspace/hackerspace.by pull request #546
Opened 2022-04-24 11:16 UTC by yahor

Апісанне задачы https://github.com/minsk-hackerspace/hackerspace.by/issues/539

2022-04-24 15:04 UTC, jekhor requested changes

2022-04-24 20:27 UTC, yahor commented on app/models/user.rb
> +      errors.add(:tariff, "You able change tariff once per 30 days.")
@jekhor а трэба? я бачыў мы лупім на інглішы памылкі.

2022-04-24 20:28 UTC, yahor commented on app/models/user.rb
> +    return if Rails.env.test? || Rails.env.development?
@jekhor для таго каб запомніць што памянялі? можа быць для гісторыі варта але вось не ведаю ці варта замарачвацца.
падаецца для девелапмента было памылкова гэта пакінута.

2022-04-24 20:29 UTC, yahor commented on app/controllers/bramnik_controller.rb
> +    if @user.present?
@jekhor minimal code cleanup

2022-04-24 20:38 UTC, jekhor commented on app/models/user.rb
> +    return if Rails.env.test? || Rails.env.development?
Ну не зусім памылкова, гэта каб адладзіць bePaid я рабіў. Таму асобным і лепей, каб git revert зрабіць пры патрэбе. Ці нейкі ўмоўны флаг зрабіць, які можна выставіць, каб уключыць адладку.

2022-04-25 10:29 UTC, yahor commented on app/models/user.rb
> +    return if Rails.env.test? || Rails.env.development?
ok. ревертну і зраблю ў іншым каміце.

2022-04-25 19:47 UTC, merged